DummyProj/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DummyProj.Models;

namespace DummyProj.Controllers
{
    public class ChartController : Controller
    {
        private TaskDbContext db = new TaskDbContext();
        //
        // GET: /Chart/

        public ActionResult Index()
        {
            return View(BarChart());
        }

        public JsonResult BarChart()
        {
            var chartData = db.Tasks.ToList();
            return Json(chartData, JsonRequestBehavior.AllowGet);
        }
    }
}

DummyProj/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DummyProj.Models;

namespace DummyProj.Controllers
{
    public class TaskController : Controller
    {
        private TaskDbContext db = new TaskDbContext();

        //
        // GET: /Task/

        public ActionResult Index()
        {
            List<SelectListItem> priorityList = new List<SelectListItem>();
            priorityList.Add(new SelectListItem { Text = "Normal", Value = "Normal" });
            priorityList.Add(new SelectListItem { Text = "Medium", Value = "Medium" });
            priorityList.Add(new SelectListItem { Text = "Urgent", Value = "Urgent" });

            SelectList priority = new SelectList(priorityList, "Value", "Text");
            ViewBag.priorityList = priority;
            //return View(db.Tasks.ToList());
            return View();
        }

        public ActionResult TaskList()
        {
            return PartialView(db.Tasks.ToList());
        }

        //
        // GET: /Task/Details/5

        public ActionResult Details(int id = 0)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            if (taskdb == null)
            {
                return HttpNotFound();
            }
            return View(taskdb);
        }

        //
        // GET: /Task/Create

        public ActionResult Create()
        {
           
            return PartialView();
        }

        //
        // POST: /Task/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskDB taskdb)
        {
            
            if (ModelState.IsValid)
            {
                db.Tasks.Add(taskdb);
                db.SaveChanges();
                return RedirectToAction("TaskList");
            }

            return RedirectToAction("TaskList");
        }

        //
        // GET: /Task/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            if (taskdb == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> priorityList = new List<SelectListItem>();
            priorityList.Add(new SelectListItem { Text = "Normal", Value = "Normal" });
            priorityList.Add(new SelectListItem { Text = "Medium", Value = "Medium" });
            priorityList.Add(new SelectListItem { Text = "Urgent", Value = "Urgent" });

            SelectList priority = new SelectList(priorityList, "Value", "Text");
            ViewBag.priorityList = priority;

            return PartialView(taskdb);
        }

        //
        // POST: /Task/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskDB taskdb)
        {
            if (!ModelState.IsValid)
            {
                var errors = GetErrorsFromModelState();
                return Json(new { success = false, errors = errors });
                //return PartialView("_Person", model);
            }
            if (ModelState.IsValid)
            {
                db.Entry(taskdb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TaskList");
            }
            return RedirectToAction("TaskList");
        }

        private Dictionary<string, ModelErrorCollection> GetErrorsFromModelState() //IEnumerable<string>
        {
            //return ModelState.SelectMany(x => x.Value.Errors
            //    .Select(error => error.ErrorMessage));

            return ModelState.Keys.Where(key => ModelState[key].Errors.Count > 0).ToDictionary(key => key, key => ModelState[key].Errors);
        }

        //
        // GET: /Task/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            if (taskdb == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("TaskList");
        }

        //
        // POST: /Task/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            db.Tasks.Remove(taskdb);
            db.SaveChanges();
            return RedirectToAction("TaskList");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Chart()
        {
            return View(BarChart());
        }

        public JsonResult BarChart()
        {
            var chartData = db.Tasks.ToList();
            return Json(chartData, JsonRequestBehavior.AllowGet);
        }
    }
}

DummyProj/Views/Chart/Chart.cshtml
@{
    ViewBag.Title = "Chart Representation";
}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
</script>
<script type="text/javascript">
    $(function () {        
        $.ajax({
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json',
            url: '@Url.Action("BarChart")',
            data: '{}',
            success: function (chartData) {
                //alert(chartData[0].Title);
                // Callback that creates and populates a data table,    
                // instantiates the pie chart, passes in the data and    
                // draws it.    

                var data = new google.visualization.DataTable();
                
                data.addColumn('string', 'Title');
                data.addColumn('number', 'RequiredHours');

                for (var i = 0; i < chartData.length; i++) {
                    data.addRow([chartData[i].Title, chartData[i].RequiredHours]);
                }

                // Instantiate and draw our chart, passing in some options
                var options = {
                    //width: 1000,
                    //height: 563,
                    hAxis: {
                        title: 'Task Title',
                        //format: 'h:mm a',
                        gridlines: { count: 10 }
                    },
                    vAxis: {
                        title: 'Required Hours'
                    }
                };
                var chart = new google.visualization.ColumnChart(document.getElementById('chartdiv'));

                chart.draw(data,
                  {
                      title: "Chart showing task Title vs. Required Hours",
                      position: "top",
                      fontsize: "14px",
                      chartArea: { width: '50%' },
                      animation: {
                          startup: true,
                          duration: 1000,
                          easing: 'out',
                      },
                      hAxis: {
                          title: 'Task Title',
                          //format: 'h:mm a',
                          minTextSpacing: 2
                      },
                      vAxis: {
                          title: 'Required Hours',
                          gridlines: { count: 10 },
                          minValue: 0,
                          maxValue: 10
                      }
                  });
            },
            error: function () {
                alert("Error loading data! Please try again.");
            }
        });
    })
</script>


    <h2>Chart Representation of Tabular Data</h2>

<div id="chartdiv" style="width: 600px; height: 350px;">
    
</div> 

@Html.ActionLink("Back to List", "Index", "Task")