DummyProj/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DummyProj.Models;

namespace DummyProj.Controllers
{
    public class ChartController : Controller
    {
        private TaskDbContext db = new TaskDbContext();
        //
        // GET: /Chart/

        public ActionResult Index()
        {
            return View(BarChart());
        }

        public JsonResult BarChart()
        {
            var chartData = db.Tasks.ToList();
            return Json(chartData, JsonRequestBehavior.AllowGet);
        }
    }
}

DummyProj/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DummyProj.Models;

namespace DummyProj.Controllers
{
    public class HomeController : Controller
    {
        private TaskDbContext db = new TaskDbContext();

        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View(db.Tasks.ToList());
        }

        //
        // GET: /Home/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    TaskDB taskdb = db.Tasks.Find(id);
        //    if (taskdb == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(taskdb);
        //}

        //
        // GET: /Home/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskDB taskdb)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(taskdb);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taskdb);
        }

        //
        // GET: /Home/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            if (taskdb == null)
            {
                return HttpNotFound();
            }
            return View(taskdb);
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskDB taskdb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taskdb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taskdb);
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            if (taskdb == null)
            {
                return HttpNotFound();
            }
            return View(taskdb);
        }

        //
        // POST: /Home/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaskDB taskdb = db.Tasks.Find(id);
            db.Tasks.Remove(taskdb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DummyProj/Views/Home/Create.cshtml
@model DummyProj.Models.TaskDB

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TaskDB</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequiredHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
   
    <fieldset>
        <legend>TaskDB</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DueDate)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.DueDate, new { @id = "dob", placeholder = "Enter Drop-off date here..." })           
            @Html.ValidationMessageFor(model => model.DueDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RequiredHours)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RequiredHours)
            @Html.ValidationMessageFor(model => model.RequiredHours)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Priority)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Priority)
            @Html.ValidationMessageFor(model => model.Priority)
        </div>

        <p>
            <input type="submit" value="Create" />
            <input type="button" value="Cancel" id="btncancel" />
        </p>
    </fieldset>
}*@

DummyProj/Views/Home/Delete.cshtml
@model DummyProj.Models.TaskDB
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>TaskDB</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DueDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DueDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequiredHours)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequiredHours)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Priority)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

DummyProj/Views/Home/Details.cshtml
@model DummyProj.Models.TaskDB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>TaskDB</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DueDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DueDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequiredHours)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequiredHours)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Priority)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.taskId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DummyProj/Views/Home/Edit.cshtml
@model DummyProj.Models.TaskDB
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TaskDB</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.taskId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @id = "dob", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequiredHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <input type="button" value="Cancel" id="btncancel" />
            </div>
        </div>
    </div>
}
@*@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TaskDB</legend>

        @Html.HiddenFor(model => model.taskId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DueDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DueDate)
            @Html.ValidationMessageFor(model => model.DueDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RequiredHours)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RequiredHours)
            @Html.ValidationMessageFor(model => model.RequiredHours)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Priority)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Priority)
            @Html.ValidationMessageFor(model => model.Priority)
        </div>

        <p>
            <input type="submit" value="Save" />
            <input type="button" value="Cancel" id="btncancel" />
        </p>
    </fieldset>
}*@

DummyProj/Views/Home/Index.cshtml
@model IEnumerable<DummyProj.Models.TaskDB>

@{
    ViewBag.Title = "Index";
}

@*<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.5/css/jquery.dataTables.css">
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
<script type="text/javascript" src="http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>*@

<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<p>Date: <input type="text" id="datepicker" /></p>
<h2>Task List</h2>
<p>
    @Html.ActionLink("Create New", "Create", null, new { id = "lnkCreate" })
    @Html.ActionLink("Tabular Representation", "Index", "Chart")
</p>
<table id="example" class="display">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequiredHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
            @*@Html.TextBoxFor(modelItem => item.DueDate, new { @id = "dob"})*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RequiredHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.taskId }, new { @class = "lnkEdit" }) |           
            @Html.ActionLink("Delete", "Delete", new { id = item.taskId }, new { @class = "lnkDelete" })
        </td>
    </tr>
}

</table>

<script>
    $(document).ready(function () {
        var url = "";

        $("#dialog-edit").dialog({
            title: 'Create User',
            autoOpen: false,
            resizable: false,
            width: 400,
            show: { effect: 'highlight' },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();
                $(this).load(url);
            }
        });

        $("#dialog-confirm").dialog({
            autoOpen: false,
            resizable: false,
            height: 170,
            width: 350,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").hide();

            },
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    window.location.href = url;
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });

        $("#lnkCreate").live("click", function (e) {
            url = $(this).attr('href');
            //alert(url);
            $(".ui-dialog-title").html("Create User");
            $("#dialog-edit").dialog('open');

            return false;
        });

        $(".lnkEdit").live("click", function (e) {
            url = $(this).attr('href');
            $(".ui-dialog-title").html("Update User");
            $("#dialog-edit").dialog('open');

            return false;
        });

        $(".lnkDelete").live("click", function (e) {
            url = $(this).attr('href');
            $("#dialog-confirm").dialog('open');

            return false;
        });

        $("#btncancel").live("click", function (e) {
            $("#dialog-edit").dialog("close");
            return false;
        });

        $("#datepicker").datepicker();

        $('#example').DataTable();
    });

    //$(function () {
    //    $("#datepicker").datepicker();
    //});
</script>